# 4.1 Exercise on Functions:

## Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L)..

In [94]:
def check(choice):
    if choice not in [1, 2]:
        raise Exception("Please enter 1 or 2")


def conversion():
    try:
        conversion_type = input("Choose type of conversion (l, w, v)")

        user_input = float(input("Enter input"))

        output = 0

        if conversion_type == "l":
            choice = int(input("Convert meters to feet (1) Convert feet to meters (2)"))
            check(choice)
            if choice == 1:
                output = user_input * 3.28
            else:
                output = user_input / 3.28
        elif conversion_type == "w":
            choice = int(input("Convert kg to pounds (1) Convert pounds to kg (2)"))
            check(choice)
            if choice == 1:
                output = user_input * 2.2
            else:
                output = user_input / 2.2
        elif conversion_type == "v":
            choice = int(input("Convert litres to gallons (1) Convert gallons to litres (2)"))
            check(choice)
            if choice == 1:
                output = user_input * 0.264
            else:
                output = user_input / 0.264
        else:
            raise Exception("Please enter l, w, or v")
        print(f"Output is {output}")
    except Exception as e:
        print(e)


conversion()

Choose type of conversion (l, w, v) l
Enter input 2
Convert meters to feet (1) Convert feet to meters (2) 232


Please enter 1 or 2


## Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spacan Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [95]:
def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False


def single_value_check(array):
    if len(array) == 1:
        return True
    return False


def sum(array):
    if single_value_check(array):
        return array[0]

    sum = 0
    for val in array:
        sum += val
    return sum


def average(array):
    if single_value_check(array):
        return array[0]

    return sum(array) / len(array)


def minimum(array):
    if single_value_check(array):
        return array[0]

    min = array[0]
    for i in range(1, len(array)):
        if min > array[i]:
            min = array[i]
    return min


def maximum(array):
    if single_value_check(array):
        return array[0]

    max = array[0]
    for i in range(1, len(array)):
        if max < array[i]:
            max = array[i]
    return max


try:
    nums_string = input("Enter numbers serperated by spaces")
    nums = nums_string.strip().split(" ")

    array = []

    if len(nums) == 1:
        raise ValueError("Empty array")
    for num in nums:
        if not is_number(num):
            raise ValueError("Invalid number")
        else:
            array.append(float(num))

    print(f"Sum is {sum(array)}")
    print(f"Average is {average(array)}")
    print(f"Min is {min(array)}")
    print(f"Max is {max(array)}")
except Exception as e:
    print(e)

Enter numbers serperated by spaces 2 4 43 6 7 3


Sum is 65.0
Average is 10.833333333333334
Min is 2.0
Max is 43.0


# 4.2 Exercise on List Manipulation:

## 1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [96]:
def extract(array):
    new_array = []
    for i in range(len(array)):
        if i % 2 == 1:
            new_array.append(array[i])
    return new_array


array = [2, 3, 4, 5, 6]
extract(array)

[3, 5]

## 2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [97]:
def get_sublist(array, start, end):
    return array[start:end+1]


start = 2
end = 4
print(f"{get_sublist([1, 2, 3, 4, 5, 6], start, end)}")

[3, 4, 5]


## 3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [98]:
def reverse_list(array):
    return array[::-1]


print(f"{reverse_list([1, 2, 3, 4])}")

[4, 3, 2, 1]


## 4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [99]:
def remove_first_last(array):
    return array[1:-1]


print(f"{remove_first_last([1, 2, 3, 4])}")

[2, 3]


## 5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [100]:
def get_first_n(array, n):
    return array[:n]


print(f"{get_first_n([1, 2, 3, 4], 2)}")

[1, 2]


## 6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [101]:
def get_last_n(array, n):
    return array[n:]


print(f"{get_last_n([1, 2, 3, 4], 2)}")

[3, 4]


## 7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [102]:
def reverse_skip(array):
    reversed_array = reverse_list(array)
    extracted_reversed_array = extract(reversed_array)
    return extracted_reversed_array


print(f"{reverse_skip([1, 2, 3, 4, 5, 6])}")

[5, 3, 1]


# 4.3 Exercise on Nested List:

## 1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [103]:
def flatten(array):
    new_array = []
    for i in array:
        for j in i:
            new_array.append(j)
    return new_array


print(f"{flatten([[2, 3], [4, 5]])}")

[2, 3, 4, 5]


## 2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [104]:
def access_nested_elements(array, indices):
    row, col = indices
    return array[row][col]


print(f"{access_nested_elements([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2])}")

6


## 3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [105]:
def sum_nested(array):
    sum = 0
    for i in array:
        if type(i) == list:
            sum += sum_nested(i)
        else:
            sum += i
    return sum


print(f"{sum_nested([[1, 2], [3, [4, 5]], 6])}")

21


## 4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [106]:
def remove_element(array, element):
    for i in array:
        for j in i:
            if j == element:
                i.remove(element)
    return array


print(f"{remove_element([[1, 2], [3, 2], [4, 5]], 2)}")

[[1], [3], [4, 5]]


## 5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [107]:
def find_max(array):
    if len(array) == 1:
        return array[0]

    for elements in array:
        if type(elements) == list:
            find_max(elements)
        else:
            max = float('-inf')
            if elements > max:
                max = elements
    return max


find_max([[1, 2], [3, [4, 5]], 6])

6

## 6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [108]:
def count_occurances(array, element):
    count = 0
    for i in array:
        for j in i:
            if j == element:
                count += 1
    return count


print(f"{count_occurances([[1, 2], [3, 2], [4, 5]], 2)}")

2


## 7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [109]:
def flatten_3(array):
    new_array = []
    for i in array:
        for j in i:
            for k in j:
                new_array.append(k)
    return new_array


print(f"{flatten_3([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])}")

[1, 2, 3, 4, 5, 6, 7, 8]


## 8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [110]:
def nested_average(array):
    sum, count = 0, 0
    for i in array:
        for j in i:
            sum += j
            count += 1
    return sum / count


print(f"{nested_average([[1, 2], [3, 4], [5, 6]])}")

3.5


# 10 To - Do - NumPy
Please complete all the problems listed below:

## 10.1 Basic Vector and Matrix Operation with Numpy.

### Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [111]:
import numpy as np

In [112]:
empty_array = np.zeros((2, 2))
empty_array

array([[0., 0.],
       [0., 0.]])

In [113]:
empty_array = np.ones((4, 2))
empty_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [114]:
fill_array = np.full((2, 2), 42)
fill_array

array([[42, 42],
       [42, 42]])

In [115]:
new_array = np.zeros_like(empty_array)
new_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [116]:
new_array = np.ones_like(empty_array)
new_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [117]:
new_list = [1, 2, 3, 4]
array = np.array(new_list)
array

array([1, 2, 3, 4])

### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [118]:
array = np.arange(10, 49)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [119]:
array = np.arange(0, 9)
np.reshape(array, (3, 3))
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
array = np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
array = np.random.random((5, 6))
array.mean()

0.5521012385949454

In [122]:
array = np.random.random((10, 10))
print(array.min(), array.max())

0.018837365068876455 0.9970188008519674


In [123]:
array = np.zeros((1, 10))
array[0][4] = 1
array

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [124]:
arr = np.array([1,2,0,0,4,0])
array = arr[::-1]
array

array([0, 4, 0, 0, 2, 1])

In [125]:
size = 5

array = np.ones((size, size))
array[1:-1, 1:-1] = 0
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [126]:
size = 8

array = np.zeros((size, size))
array[1::2, ::2] = 1
array[::2, 1::2] = 1
array

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [127]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [128]:
x + y

array([[ 6,  8],
       [10, 13]])

In [129]:
x - y

array([[-4, -4],
       [-4, -3]])

In [130]:
x * 2

array([[ 2,  4],
       [ 6, 10]])

In [131]:
v.dot(w)

219

In [132]:
x.dot(v)

array([29, 77])

In [133]:
x.dot(y)

array([[19, 22],
       [50, 58]])

In [134]:
np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

47

In [135]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A1 = np.linalg.inv(A)
A.dot(A1)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [136]:
np.dot(A, B)

array([[23, 13],
       [51, 29]])

In [137]:
np.dot(B, A)

array([[36, 44],
       [13, 16]])

In [138]:
np.transpose(np.dot(A, B))

array([[23, 51],
       [13, 29]])

In [139]:
np.dot(np.transpose(B), np.transpose(A))

array([[23, 51],
       [13, 29]])

In [140]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A, B

(array([[ 2, -3,  1],
        [ 1, -1,  2],
        [ 3,  1, -1]]),
 array([-1, -3,  9]))

In [141]:
X = np.linalg.inv(A).dot(B)
X

array([ 2.,  1., -2.])

## 10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

### 1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [142]:
import time


def python(array1, array2):
    new_array = []
    for i in range(len(array1)):
        for j in range(len(array1[i])):
            new_array.append([array1[i][j] + array2[i][j]])
    return new_array


def numpy(array1, array2):
    new_array = np.zeros_like(array1)
    new_array = array1 + array2
    return new_array


array1 = np.random.random((5000, 200))
array2 = np.random.random((5000, 200))

lst1 = array1.tolist()
lst2 = array2.tolist()

start = time.time()
python(lst1, lst2)
end = time.time()
diff_python = end - start

start = time.time()
numpy(array1, array2)
end = time.time()
diff_numpy = end - start

print(f"Python time: {diff_python}")
print(f"Numpy time: {diff_numpy}")

Python time: 0.876798152923584
Numpy time: 0.003999471664428711


### 2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [143]:
import time


def python(array1, array2):
    new_array = []
    for i in range(len(array1)):
        for j in range(len(array1[i])):
            new_array.append([array1[i][j] * array2[i][j]])
    return new_array


def numpy(array1, array2):
    new_array = np.zeros_like(array1)
    new_array = array1 * array2
    return new_array


array1 = np.random.random((5000, 200))
array2 = np.random.random((5000, 200))

lst1 = array1.tolist()
lst2 = array2.tolist()

start = time.time()
python(lst1, lst2)
end = time.time()
diff_python = end - start

start = time.time()
numpy(array1, array2)
end = time.time()
diff_numpy = end - start

print(f"Python time: {diff_python}")
print(f"Numpy time: {diff_numpy}")

Python time: 0.7656259536743164
Numpy time: 0.004536151885986328


### 3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [144]:
import time


def python(array1, array2):
    new_array = []
    for i in range(len(array1)):
        for j in range(len(array1[i])):
            new_array.append([array1[i][j] * array2[i][j]])
    return new_array


def numpy(array1, array2):
    new_array = np.sum(np.multiply(array1, array2))
    return new_array


array1 = np.random.random((5000, 200))
array2 = np.random.random((5000, 200))

lst1 = array1.tolist()
lst2 = array2.tolist()

start = time.time()
python(lst1, lst2)
end = time.time()
diff_python = end - start

start = time.time()
numpy(array1, array2)
end = time.time()
diff_numpy = end - start

print(f"Python time: {diff_python}")
print(f"Numpy time: {diff_numpy}")

Python time: 0.7847630977630615
Numpy time: 0.004000425338745117


### 4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [145]:
import time


def python_matrix_mult(matrix1, matrix2):
    result = []
    for row in matrix1:
        row_result = []
        for col in zip(*matrix2):
            sum_value = 0
            for a, b in zip(row, col):
                sum_value += a * b
            row_result.append(sum_value)
        result.append(row_result)
    return result


def numpy_matrix_mult(matrix1, matrix2):
    return np.dot(matrix1, matrix2)


matrix1 = np.random.random((1000, 1000))
matrix2 = np.random.random((1000, 1000))

lst1 = matrix1.tolist()
lst2 = matrix2.tolist()

start = time.time()
python_matrix_mult(lst1, lst2)
end = time.time()
diff_python = end - start

start = time.time()
numpy_matrix_mult(matrix1, matrix2)
end = time.time()
diff_numpy = end - start

print(f"Python time: {diff_python} seconds")
print(f"NumPy time: {diff_numpy} seconds")

Python time: 73.57296514511108 seconds
NumPy time: 0.02104496955871582 seconds
